# Generated by Django 5.2 on 2025-04-14 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_area_property_bathrooms_property_bedrooms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur/Bailleur'),
        ),
        migrations.AddField(
            model_name='property',
            name='seller_type',
            field=models.CharField(choices=[('owner', 'Propriétaire'), ('agent', 'Agent immobilier'), ('developer', 'Promoteur')], default='owner', max_length=20, verbose_name='Type de vendeur'),
        ),
    ]
